version: '3.8'

services:
  go:
    container_name: go
    image: golang:1.19.3
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/go/src
    networks:
      - go_tutorial
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  db:
    container_name: mysql
    restart: always
    image: mysql:8.0
    tty: true
    platform: linux/x86_64
    ports:
      - "53306:3306"
    environment:
      MYSQL_DATABASE: 'recordings'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data-mysql:/var/lib/mysql
      - ./docker-conf/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker-conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - go_tutorial

volumes:
  data-mysql:

networks:
  go_tutorial: